name: Run Image and Display Name

on:
  push:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  run-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Docker Image and Display Name
      run: ./run_and_display.sh
